## Time Series Split

In [1]:
#libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import TimeSeriesSplit

from scipy.stats import boxcox

from sklearn.metrics import mean_absolute_percentage_error, mean_absolute_error, r2_score, mean_squared_error

import warnings

warnings.filterwarnings('ignore')

from IPython.display import display, Markdown

pd.set_option('display.max_rows', 999)
pd.set_option('display.max_columns', 999)
pd.set_option('display.width', 800)
pd.set_option('display.max_colwidth', None)
pd.options.display.float_format = '{:.5f}'.format

In [8]:
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4, 5, 6])

In [11]:
tscv = TimeSeriesSplit()
print(tscv)

TimeSeriesSplit(max_train_size=None, n_splits=3)

for train_index, test_index in tscv.split(X):
    print('TRAIN:', train_index, 'TEST:', test_index) 
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    print('X_train')
    print(X_train)
    print('X_test')
    print(X_test)

TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None)
TRAIN: [0] TEST: [1]
X_train
[[1 2]]
X_test
[[3 4]]
TRAIN: [0 1] TEST: [2]
X_train
[[1 2]
 [3 4]]
X_test
[[1 2]]
TRAIN: [0 1 2] TEST: [3]
X_train
[[1 2]
 [3 4]
 [1 2]]
X_test
[[3 4]]
TRAIN: [0 1 2 3] TEST: [4]
X_train
[[1 2]
 [3 4]
 [1 2]
 [3 4]]
X_test
[[1 2]]
TRAIN: [0 1 2 3 4] TEST: [5]
X_train
[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]]
X_test
[[3 4]]


In [6]:
# Fix test_size to 2 with 12 samples
X = np.random.randn(12, 2)
y = np.random.randint(0, 2, 12)
tscv = TimeSeriesSplit(n_splits=3, test_size=2)
for train_index, test_index in tscv.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]

TRAIN: [0 1 2 3 4 5] TEST: [6 7]
TRAIN: [0 1 2 3 4 5 6 7] TEST: [8 9]
TRAIN: [0 1 2 3 4 5 6 7 8 9] TEST: [10 11]
